### PR TITLE
add .idea to gitignore

### PR DESCRIPTION
**Pull request by KeloDraken**
Removed .idea folder and added .idea to gitignore

### CODE REVIEW

**Review by CursoryWaif32 — CHANGES_REQUESTED** [review]
Also need to remove those .iml and .xml files

**Comment by KeloDraken** [comment]
> Also need to remove those .iml and .xml files

should ignore all .iml files?

**Comment by CursoryWaif32** [comment]
I believe so, we can change that if we specifically need to add a .iml file. but as far as I am aware we should ignore them.

**Comment by CursoryWaif32** [comment]
and obviously don't delete the pom.xml, just any other weird autocreated .xml files

**Review by CursoryWaif32 — APPROVED** [review]
nice.

**Pull request merged**
